### ISSUE TITLE
nerdtree plugin link changed

### ISSUE THREAD

**Issue by rsharifnasab** [1995parham/dotfiles#14]
hi, i was watching your nvim init file in `dotfiles/nvim/init.vim`
look at  nerdtree plugin in line 208
```
Plug 'scrooloose/nerdtree'         " A tree explorer plugin for vim.
```
i think the link changed from [old link](https://github.com/scrooloose/nerdtree) to [this new link](https://github.com/preservim/nerdtree)
as you can see the old link will redirect to new link too, but maybe you should consider changing link 

BTW I'm not much familiar with GitHub issues, excuse me.

**Comment by 1995parham** [comment]
Thanks for reporting it, I have updated it. Make these links working all the times is one the most significant issue that I have and I only change them when there is an error on `PlugUpdate` or `PlugInstall`
