### ISSUE TITLE
error occurred while runing ./start.sh env and vim can't find naz color scheme

### ISSUE THREAD

**Issue by geekn0rd** [1995parham/dotfiles#18]
### First of all thanks for sharing your dotfiles with the world:) 

  
[env] dependencies: neovim
[env] do you want to install dependencies?[Y/n] Y
[neovim] install edge version of neovim and general checkers/linters
                       _
 _ __   ___  _____   _(_)_ __ ___
| |_ \ / _ \/ _ \ \ / / | |_ ` _ \
| | | |  __/ (_) \ V /| | | | | | |
|_| |_|\___|\___/ \_/ |_|_| |_| |_|

  
[neovim] dependencies: node shell
[neovim] do you want to install dependencies?[Y/n] Y
[node] install nodejs, remembers neovim-coc always needs nodejs

                 _
 _ __   ___   __| | ___
| |_ \ / _ \ / _| |/ _ \
| | | | (_) | (_| |  __/
|_| |_|\___/ \__|_|\___|

  
[node] linux with apt (ubuntu?)
[node] installing node from its official apt repository

## Populating apt-get cache...

+ apt-get update
Hit:1 http://ppa.launchpad.net/bartbes/love-stable/ubuntu focal InRelease                                                                                                                                  
Hit:2 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                            
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                                     
Hit:4 http://archive.canonical.com/ubuntu focal InRelease                                                            
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                                                    
Hit:6 https://download.mono-project.com/repo/ubuntu stable-focal InRelease
Ign:7 http://ppa.launchpad.net/cs50/ppa/ubuntu focal InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease      
Hit:9 http://ppa.launchpad.net/devacom/gnome-40/ubuntu focal InRelease   
Hit:10 http://us.archive.ubuntu.com/ubuntu focal-security InRelease      
Hit:11 http://ppa.launchpad.net/devacom/x11/ubuntu focal InRelease       
Hit:12 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Err:6 https://download.mono-project.com/repo/ubuntu stable-focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
Ign:13 http://ppa.launchpad.net/towolf/transparent-gnome-terminal/ubuntu focal InRelease
Err:14 http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Err:15 http://ppa.launchpad.net/towolf/transparent-gnome-terminal/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.mono-project.com/repo/ubuntu stable-focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
E: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/towolf/transparent-gnome-terminal/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by 1995parham** [comment]
@geekn0rd Thanks for using my dotfiles, I think the issue is related to apt installation of nodejs, you can bypass this section by saying no to see what happens next and let me know.

**Comment by geekn0rd** [comment]
@1995parham I had some obsolete apt repositories, I removed them and it works fine :),
now the issue is when I want to use vim or nvim:
### nvim:

E5113: Error while calling lua chunk: /home/amir-ali/.config/nvim/lua/c
.lua:4: module 'which-key' not found:
        no field package.preload['which-key']
        no file './which-key.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit
ta3/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key.lua'
        no file '/usr/local/share/lua/5.1/which-key/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.
ey.lua'-k
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.
ey/init.lua'
        no file './which-key.so'
        no file '/usr/local/lib/lua/5.1/which-key.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/
.so'h-key
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/amir-ali/.config/nvim/lua/config/key.lua:4: in main chunk
        [C]: in function 'require'
-- More --

### vim (I found naz color scheme on your GitHub bu couldn't install it):
Error detected while processing /home/amir-ali/.vimrc:
line  181:
E185: Cannot find color scheme 'naz'
Press ENTER or type command to continue

**Comment by 1995parham** [comment]
Sure, In this step you must install the required packages with `:PacketSync` as neovim command, it will install the required packages like naz and etc.

**Comment by geekn0rd** [comment]
Thanks again, `:PacketSync` on nvim and `:PlugInstall` on vim made it work,
there's only one thing remaining :) all the icons are missing e.g. tab section in vim 
doesn't have the 'x' icon, cpu diagram is missing etc.
![last](https://user-images.githubusercontent.com/70889826/147857255-7053cff5-b828-4207-a593-876e53cdf584.png)

**Comment by 1995parham** [comment]
I always use neovim so I didn't pay attention to vim font issue but you can try the following

```
./start.sh font
```

to install some useful fonts but I am not sure that it can solve this issue. Also again thanks for using my dotfiles and it would be great if you can create a PR for your issues so others can solve them faster

**Comment by geekn0rd** [comment]
I have to say it this was my 1st PR :))
appreciate the opportunity.
