### ISSUE TITLE
macOS alternatives

### ISSUE THREAD

**Issue by rsharifnasab** [1995parham/dotfiles#46]
Few applications can be installed in Mac as well as Arch Linux, but they are mentioned as "-" in the `readme.md`

+ Calendar: `cal` is available, `jcal` is also available with `brew install jcal`
+ The fetch software packages are also available, although `screenfetch` doesn't work well. So we can name `tokei` and `onefetch`
+ Top: btop is available with brew install `btop`.
+ Speedtest also offers a macOS client, available via: `brew install speedtest-cli`. 
+ Latex: On macOS, one can have `tectonic`, which is handy and easy to install; in addition to that, a good TeX distribution is `mactex`, which is batteries included TeX distribution, although installation size is enormous (~5GB). It could be installed with `brew install mactex`.
+ Finally, `tldr`, `jq`, and `jless` are also available to download easily with brew.

**Comment by 1995parham** [comment]
I am not using OSX for a while, so I really appreciate for mentioning these. I will update README and related scripts.
