### ISSUE TITLE
Migrate from i3 to Awesome

### ISSUE THREAD

**Issue by 1995parham** [1995parham/dotfiles#61]
After trying [i3](https://i3wm.org/) for a while again, I decided to give [Awesome](https://awesomewm.org/) a shot.

- [awesome - ArchWiki](https://wiki.archlinux.org/title/Awesome)
- [ArchInstall's awesome profile](https://github.com/archlinux/archinstall/blob/master/archinstall/default_profiles/desktops/awesome.py)
- [Awful DOTS](https://github.com/Amitabha37377/Awful-DOTS)

**Comment by 1995parham** [comment]
@rsharifnasab you can give a shoot too, it is beautiful :heart_eyes:

**Comment by rsharifnasab** [comment]
Didn't you switch to macOS? What's up with the Linux window managers?

**Comment by rsharifnasab** [comment]
Btw thank you, I'm still struggling to make my wifi and sleep stable :)))

**Comment by 1995parham** [comment]
> Didn't you switch to macOS? What's up with the Linux window managers?

Yes, I am just using them for fun over my PC which isn't useful for work, you can consider this as NSFW 😂

**Comment by 1995parham** [comment]
> Btw thank you, I'm still struggling to make my wifi and sleep stable :)))

These sleeply things are the hardest part. After using Linux, I even shutdown my macOS 😂
